
class Product:
    _Product_code = []
    _Product_title = []
    _Product_title_ukr = []
    _Product_description = []
    _Product_description_ukr = []
    _Product_pictures = []
    _Product_price = []
    _Product_availability = []
    _Product_IP_item = []
    _Product_currencyId = []
    _Product_Unit_measurement = []
    _Product_country_of_origin = []
    _Product_vendor = []
    _Product_Item_type = []
    _Product_price_file = []
    _Product_Note = []
    _Pics = []
    _Product_pic_str = []